version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["http://localhost:8083"]  # Permet l'accès depuis l'interface web
    Access-Control-Allow-Methods: ["GET", "PUT", "POST", "DELETE", "OPTIONS"]
    Access-Control-Allow-Headers: ["Authorization", "Content-Type"]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
