version: '3.8'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - registry_network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "8083:80"
    environment:
      - REGISTRY_TITLE=SUPMIT Private Registry
      - REGISTRY_URL=http://registry:5000  # URL du registre Docker
    depends_on:
      - registry
    networks:
      - registry_network

volumes:
  registry_data:

networks:
  registry_network:
    driver: bridge
